frontend:
  image:
    repository: 742710068961.dkr.ecr.ap-south-1.amazonaws.com/my-app/frontend
    tag: latest
    pullPolicy: IfNotPresent

  replicas: 2

  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: 742710068961.dkr.ecr.ap-south-1.amazonaws.com/my-app/backend
    tag: latest
    pullPolicy: IfNotPresent

  replicas: 2

  service:
    type: ClusterIP
    port: 3000

  env:
    DB_HOST: mydb.c3cay4ksor3z.ap-south-1.rds.amazonaws.com:3306
    DB_NAME: testdb

db:
  host: mydb.c3cay4ksor3z.ap-south-1.rds.amazonaws.com:3306
  name: testdb

secrets:
  dbUser: admin
  dbPassword: password

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}
